import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import {Providers} from "@/components/providers";
import { Indie_Flower } from 'next/font/google';



const RalewaySans = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${RalewaySans.className} antialiased`}
        >
        <Providers>
        <NavBar/>
        {children}
    </Providers>
      </body>
    </html>
  );
}
